aluguel_imoveis/aluguel_imoveis/urls.py
from django.contrib import admin
from django.urls import path, include
from imoveis import urls as imoveis_urls
from imoveis import views as imoveis_views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
	path('', imoveis_views.ImovelList.as_view()),
    path('admin/', admin.site.urls),
    path('imoveis/', include(imoveis_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aluguel_imoveis/imoveis/urls.py
from django.urls import path
from .views import ImovelList
from .views import ImovelDetail
from .views import ImovelCreate
from .views import ImovelUpdate
from .views import ImovelDelete

urlpatterns = [
	path('imovel_list/', ImovelList.as_view(), name='imovel_list'),
	path('imovel_detail/<int:pk>', ImovelDetail.as_view(), name="imovel_detail"),
	path('imovel_create/', ImovelCreate.as_view(), name="imovel_create"),
	path('imovel_update/<int:pk>', ImovelUpdate.as_view(), name="imovel_update"),
	path('imovel_delete/<int:pk>', ImovelDelete.as_view(), name="imovel_delete"),


]

aluguel_imoveis/imoveis/models.py
from django.db import models

class Imovel(models.Model):
	titulo = models.CharField(max_length=40)
	valor = models.DecimalField(max_digits=6, decimal_places=2)
	descricao = models.TextField()
	cep = models.CharField(max_length=10, blank=True, null=True)
	bairro = models.CharField(max_length=60, null=True)
	cidade = models.CharField(max_length=70, null=True)
	logradouro = models.CharField(max_length=150, null=True)
	numero = models.IntegerField(null=True, blank=True)
	complemento = models.CharField(max_length=100, null=True, blank=True)
	uf = models.CharField(max_length=30, null=True)
	foto = models.ImageField(null=True, blank=True)

	class Meta():
		verbose_name_plural = "Imóveis"

	def image_url(self):
		if self.foto and hasattr(self.foto, 'url'):
			return self.foto.url

	def __str__(self):
		return self.titulo

aluguel_imoveis/imoveis/forms.py
from django.forms import ModelForm
from .models import Imovel

class ImovelForm(ModelForm):

	class Meta:
		model = Imovel
		fields = '__all__'
		widgets = {
			'cep': forms.TextInput(attrs={'placeholder': 'cep'})
		}

aluguel_imoveis/imoveis/views.py
from django.shortcuts import render
from .models import Imovel
from django.urls import reverse_lazy
from django.db.models import Q
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView
from django.views.generic.edit import DeleteView
from viacep_package import viacep


class ImovelList(ListView):
	model = Imovel
	template_name = 'imoveis/imovel_list.html'

	def get_queryset(self):
		query = self.request.GET.get('q')
		if query:
			d = viacep.ViaCEP(query)
			data = d.getDadosCEP()
			if data:
				#pesquisas por CEP mostram os imóveis do mesmo bairro
				#sendo possível mostrar os da mesma cidade, alterando o 
				#parametro no filter para cidade
				cidade = data['localidade']
				bairro = data['bairro']
				return Imovel.objects.filter(
							Q(bairro=bairro))						
			else:
				return Imovel.objects.filter(
							Q(cidade=query)|
							Q(bairro=query))
		else:
			return Imovel.objects.all()

class ImovelDetail(DeleteView):
	model = Imovel
	template_name = 'imoveis/imovel_detail.html'


class ImovelCreate(CreateView):
	model = Imovel
	template_name = 'imoveis/imovel_form.html'
	fields = ['titulo','valor','descricao','cep','bairro','cidade','logradouro','numero','complemento','uf','foto']
	success_url = reverse_lazy('imovel_list') 


class ImovelUpdate(UpdateView):
	model = Imovel
	fields = ['titulo','valor','descricao','cep','bairro','cidade','logradouro','numero','complemento','uf','foto']
	template_name = 'imoveis/imoveis_update_form.html'
	success_url = 	reverse_lazy('imovel_list') 


class ImovelDelete(DeleteView):
	model = Imovel
	template_name = 'imoveis/imovel_confirm_delete.html'
	success_url = reverse_lazy('imovel_list')

aluguel_imoveis/imoveis/templates/imoveis/imoveis_update_form.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block main %}
<h2>Editar Imóvel</h2>
<h4>(Entre com um CEP real)</h4>

	<form action="" method="post" enctype="multipart/form-data">           
		{% csrf_token %}
    	{{ form.as_p }}
    	<input type="submit" value="Update" />
	</form>
	<script src="http://code.jquery.com/jquery-3.0.0.min.js"></script>
	<script>
		$("#id_cep").blur(function(){
			var cep = this.value.replace(/[^0-9]/, "");
			if(cep.length != 8){
				return false;
			}
			var url = "http://viacep.com.br/ws/"+cep+"/json/";
			$.getJSON(url, function(dadosRetorno){
				try{
					$("#id_logradouro").val(dadosRetorno.logradouro);
					$("#id_bairro").val(dadosRetorno.bairro);
					$("#id_cidade").val(dadosRetorno.cidade);
					$("#id_cidade").val(dadosRetorno.localidade);
					$("#id_uf").val(dadosRetorno.uf);
				}catch(ex){}
			});
		});
	</script>

{% endblock %}

aluguel_imoveis/imoveis/templates/imoveis/imovel_confirm_delete.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block main %}
<form action="" method="post">{% csrf_token %}
    <p>Tem certeza que deseja excluir imóvel "{{ object.titulo }}"?</p>
    <input type="submit" value="Confirm" />
</form>
{% endblock %}

aluguel_imoveis/imoveis/templates/imoveis/imovel_detail.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block main %}

<h1>{{ imovel.titulo }}</h1>
<h2>R$ {{ imovel.valor }}<br>
{{ imovel.descricao }}<br>
{{ imovel.cep }}<br>
{{ imovel.bairro }}<br>
{{ imovel.cidade }}<br>
{{ imovel.logradouro }}<br>
{{ imovel.numero }}<br>
{{ imovel.complemento }}<br>

<img src="{{ imovel.image_url }}">
<a href="{% url 'imovel_update' imovel.pk %}">Editar</a>
<a href="{% url 'imovel_list' %}">Home</a>
<a href="{% url 'imovel_delete' imovel.pk %}">Deletar</a>
{% endblock %}

aluguel_imoveis/imoveis/templates/imoveis/imovel_form.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block main %}
<div class="row">
	<div class="col-6">
		<h2>Novo Imóvel</h2>
		<h4>(Entre com um CEP real)</h4><br>
		<form action="" method="post" enctype="multipart/form-data">           
			{% csrf_token %}
	    	{{ form|bootstrap }}
	    	<input type="submit" value="Save" />
		</form>
	</div>
</div>
	<script src="http://code.jquery.com/jquery-3.0.0.min.js"></script>
	<script>
		$("#id_cep").blur(function(){
			var cep = this.value.replace(/[^0-9]/, "");
			if(cep.length != 8){
				return false;
			}
			var url = "http://viacep.com.br/ws/"+cep+"/json/";
			$.getJSON(url, function(dadosRetorno){
				try{
					$("#id_logradouro").val(dadosRetorno.logradouro);
					$("#id_bairro").val(dadosRetorno.bairro);
					$("#id_cidade").val(dadosRetorno.cidade);
					$("#id_cidade").val(dadosRetorno.localidade);
					$("#id_uf").val(dadosRetorno.uf);
				}catch(ex){}
			});
		});
	</script>

{% endblock %}

aluguel_imoveis/imoveis/templates/imoveis/imovel_list.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block main %}
<div class="row">
	<div class="col">
	</div>
	<div class="col-10">
		<form class="GET">
			<input class="searchfield" name="q" value="{{ request.GET.q }}" placeholder="CEP, bairro ou cidade"/>
			<button type="submit">Search</button>
		</form>
		<h1>Listagem de Imóveis</h1>
		<a href="{% url 'imovel_list' %}">  Home  </a> 
		<a href="{% url 'imovel_create' %}">  Novo  </a> 	
		<table class="table">
		  <thead>
		    <tr>
		      <th scope="col"></th>
		      <th scope="col">Descrição</th>
		      <th scope="col">Cidade</th>
		      <th scope="col">Bairro</th>
		      <th scope="col"></th>
		    </tr>
		  </thead>
		  <tbody>
		  	{% for imovel in imovel_list %}
			    <tr>
			      <th scope="row">{{ imovel.pk }}</th>
			      <td><a href="{% url 'imovel_detail' imovel.pk %}">{{ imovel.titulo }}</a></td>
			      <td>{{ imovel.cidade }}</td>
			      <td>{{ imovel.bairro }}</td>
			      <td><img src="{{ imovel.image_url|default_if_none:'#' }}"></td>
			    </tr>
			{% endfor %}
		  </tbody>
		</table>

	</div>
	<div class="col">
	</div>
</div>

{% endblock %}

aluguel_imoveis/templates/base.html
<!doctype html>
<html>
<head>
  <meta charset="UTF-8"/>
  <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <title>{% block title %}{% endblock %}</title>
</head>
<body>

  <div class="container">
    {% block main %}
    {% endblock %}
  </div>

  {% block footer %}
  {% endblock %}

</body>
</html>